### ISSUE TITLE
模块导入问题

### ISSUE THREAD

**Issue by niminjian** [mext169/detect-and-recognize-mask-face#2]

**Comment by niminjian** [comment]
您好，请问您在real_time.py文件中用的face2模块是啥，我通过各种方式未找到它的安装命令

**Comment by mext169** [comment]
face2是一个python文件，里面包含了定义了相关函数和class，face2.py和real_time.py在同一个路径下，用import导入就可以了

**Comment by niminjian** [comment]
明白了，谢谢大佬，一开始我把它当做一个python的默认库了
